// Generated by build_data.py — do not edit directly.
// Run `python build_data.py` after updating classifications.json.

const IMG = [
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.34.jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.36 (1).jpeg' },
  { cat: 'presentoirs', file: 'WhatsApp Image 2026-06-09 at 02.12.36 (2).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.12.36.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.46 (1).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.12.46 (2).jpeg' },

  { cat: 'habillage-vehicules', file: 'WhatsApp Image 2026-06-09 at 02.12.47 (1).jpeg' },
  { cat: 'bureau-vente', file: 'WhatsApp Image 2026-06-09 at 02.12.47 (2).jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.47 (3).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.47.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (1).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (2).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (3).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (4).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (5).jpeg' },
  { cat: 'signaletique-interieure', file: 'WhatsApp Image 2026-06-09 at 02.12.48 (6).jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.48.jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.12.49 (1).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.12.49 (2).jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.49 (3).jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 02.12.49 (4).jpeg' },
  { cat: 'signaletique-interieure', file: 'WhatsApp Image 2026-06-09 at 02.12.49.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.36.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.37 (1).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.37 (2).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.37.jpeg' },
  { cat: 'impression-numerique', file: 'WhatsApp Image 2026-06-09 at 02.31.47 (1).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.47.jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.48 (1).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.48 (2).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.48.jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.51 (1).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.51 (2).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.51 (3).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.51.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (1).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (2).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (3).jpeg' },
  { cat: 'palissades', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (4).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (5).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 02.31.52 (6).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 02.31.52.jpeg' },

  { cat: 'habillage-vehicules', file: 'WhatsApp Image 2026-06-09 at 02.31.53 (5).jpeg' },

  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 03.19.17.jpeg' },
  { cat: 'palissades', file: 'WhatsApp Image 2026-06-09 at 03.33.33.jpeg' },
  { cat: 'bipole', file: 'WhatsApp Image 2026-06-09 at 03.33.37 (1).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 03.33.40.jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 03.33.41 (1).jpeg' },
  { cat: 'signaletique-interieure', file: 'WhatsApp Image 2026-06-09 at 03.33.41.jpeg' },
  { cat: 'bipole', file: 'WhatsApp Image 2026-06-09 at 03.33.43.jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 15.59.59 (1).jpeg' },
  { cat: 'impression-numerique', file: 'WhatsApp Image 2026-06-09 at 15.59.59 (2).jpeg' },
  { cat: 'panneaux-toiture', file: 'WhatsApp Image 2026-06-09 at 15.59.59 (3).jpeg' },
  { cat: 'palissades', file: 'WhatsApp Image 2026-06-09 at 16.00.00 (2).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 16.00.00 (3).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 16.00.00 (4).jpeg' },
  { cat: 'habillage-magasins', file: 'WhatsApp Image 2026-06-09 at 16.00.00 (6).jpeg' },
  { cat: 'totems', file: 'WhatsApp Image 2026-06-09 at 16.00.00.jpeg' },
];

const VIDEOS = [
  { cat: 'hero', file: 'WhatsApp Video 2026-06-09 at 02.12.48.mp4' },
  { cat: 'hero', file: 'WhatsApp Video 2026-06-09 at 02.31.51.mp4' },
];

const catNames = {
  'panneaux-sol-geants': 'Panneaux bipôles géants',
  'panneaux-toiture': 'Panneaux sur toiture',
  'signaletique-interieure': 'Signalétique intérieure',
  'presentoirs': 'Totems en découpe',
  'palissades': 'Palissades',
  'habillage-vehicules': 'Habillage de véhicules',
  'bureau-vente': 'Habillage de façade de showroom',
  'habillage-magasins': 'Habillage de magasin',
  'impression-numerique': 'Impression numérique',
  'panneaux-affichage': 'Affichage mural géant',
  'stands': 'Stands',
  'totems': 'Totems géants',
};

const catContext = {
  'panneaux-sol-geants': { problem: 'Annonces de grande envergure invisibles', solution: 'Panneau bipôle géant implanté au sol', result: 'Captation immédiate du regard' },
  'panneaux-toiture': { problem: 'Toiture inexploitée', solution: 'Panneau sur toiture visible des axes', result: 'Visibilité maximale' },
  'signaletique-interieure': { problem: 'Visiteurs perdus dans vos locaux', solution: 'Signalétique intérieure claire', result: 'Guidage fluide et esthétique' },
  'presentoirs': { problem: 'Totem sans forme distinctive', solution: 'Totem en découpe sur mesure', result: 'Image marquante et mémorable' },
  'palissades': { problem: 'Palissade nue, image négative', solution: 'Habillage de palissade esthétique', result: 'Valorisation du chantier' },
  'habillage-vehicules': { problem: 'Véhicules qui passent inaperçus', solution: 'Habillage publicitaire sur mesure', result: 'Marque mobile 24h/24' },
  'bureau-vente': { problem: 'Façade de showroom sans impact', solution: 'Habillage de façade de showroom', result: 'Attraction et conviction renforcées' },
  'habillage-magasins': { problem: 'Vitrine qui n\'attire pas le regard', solution: 'Habillage de magasin sur mesure', result: 'Attraction client renforcée' },
  'impression-numerique': { problem: 'Supports sans rendu professionnel', solution: 'Impression grand format HD', result: 'Rendu éclatant' },
  'panneaux-affichage': { problem: 'Mur sans signal publicitaire', solution: 'Affichage mural géant', result: 'Impact maximal sur les passants' },
  'stands': { problem: 'Stand qui ne se démarque pas', solution: 'Stand sur mesure image de marque', result: 'Différenciation en salon' },
  'totems': { problem: 'Entrée sans signal fort', solution: 'Totem géant haute visibilité', result: 'Identification à distance' },
};

const catList = ['panneaux-sol-geants', 'panneaux-toiture', 'signaletique-interieure', 'presentoirs', 'palissades',  'habillage-vehicules', 'bureau-vente', 'habillage-magasins', 'impression-numerique', 'panneaux-affichage', 'stands', 'totems'];

const COVERS = {
  'totems': 'WhatsApp Image 2026-06-09 at 02.12.34.jpeg',
  'presentoirs': 'WhatsApp Image 2026-06-09 at 02.12.48.jpeg',
  'panneaux-toiture': 'WhatsApp Image 2026-06-09 at 02.31.52 (6).jpeg',
  'habillage-magasins': 'WhatsApp Image 2026-06-09 at 02.31.52 (1).jpeg',
  'habillage-vehicules': 'WhatsApp Image 2026-06-09 at 02.12.47 (1).jpeg',
  'bureau-vente': 'WhatsApp Image 2026-06-09 at 03.19.17.jpeg',
  'signaletique-interieure': 'WhatsApp Image 2026-06-09 at 02.12.49.jpeg',
  'impression-numerique': 'WhatsApp Image 2026-06-09 at 02.31.47 (1).jpeg',
  'palissades': 'WhatsApp Image 2026-06-09 at 02.31.52 (4).jpeg',
  'panneaux-sol-geants': 'WhatsApp Image 2026-06-09 at 03.33.37 (1).jpeg',
  'panneaux-affichage': 'WhatsApp Image 2026-06-09 at 02.12.46.jpeg',
  'stands': 'WhatsApp Image 2026-06-09 at 16.00.00.jpeg',
};

const path = (f) => `img/${f.replace(/ /g, '%20')}`;